version: '3.3'

x-service_defaults: &service_defaults
    env_file:
      - ./.env
      - ../.env
    volumes:
      - ../:/workspace

services:
  devcontainer:
    # << : *service_defaults
    build:
      context: ./
      dockerfile: devcontainer/devcontainer.containerfile
    volumes:
      - ../:/workspace
      - /Users/ronan/.ssh:/root/.ssh:ro
      - /Users/ronan/.terminus:/root/.terminus
      # - ../data/homedir:/root/
    links:
      - db
      - gateway:report.local
      - gateway:drupal.local
      - gateway:backstop.local
      - gateway:reference.local
    env_file:
      - ./.env
      - ../.env

  gateway:
    # << : *service_defaults
    image: nginx:1.25
    links:
      - app
    ports:
      - 80:80
      - 8010
      - 8100
    volumes:
      - ../:/workspace
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf

  app:
    << : *service_defaults
    build:
      context: ./
      dockerfile: app/app.containerfile
    links:
      - db
    expose:
      - 9000

  db:
    << : *service_defaults
    image: mariadb:11
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf:ro

  phpmyadmin:
    << : *service_defaults
    image: phpmyadmin:5
    ports:
      - 80

  # sitespeed:
  #   image: backstopjs/backstopjs
  #   links:
  #     - gateway:drupal.local
  #   volumes:
  #     - ../data/sitespeed.io:/sitespeed.io

  backstop:
    << : *service_defaults
    image: backstopjs/backstopjs
    command: --config="/workspace/.devcontainer/backstop.js/backstop.config.js" remote
    links:
      - gateway:drupal.local
      - gateway:backstop.local
      - gateway:reference.local
