version: '3.3'

services:
  devcontainer:
    build:
      context: ./
      dockerfile: devcontainer/devcontainer.containerfile
    volumes:
      - ../:/workspace
    links:
      - d9gateway:drupal9
      - gateway:drupal10
    env_file:
      - .env 

  d9gateway:
    image: nginx:1.25
    links:
      - d9app
    ports:
      - "8009:80"
    volumes:
      - ../:/workspace
      - ./drupal9/nginx.conf:/etc/nginx/nginx.conf

  d9app:
    build:
      context: ./
      dockerfile: drupal9/drupal9.containerfile
    links:
      - db
    volumes:
      - ../:/workspace
    env_file:
      - .env

  gateway:
    image: nginx:1.25
    links:
      - d10app
      - d9app
    ports:
      - "8010:80"
    volumes:
      - ../:/workspace
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf

  d10app:
    build:
      context: ./
      dockerfile: drupal10/drupal10.containerfile
    links:
      - db
    volumes:
      - ../:/workspace
      - ../src/modules:/workspace/drupal10/web/modules/custom
      - ../src/themes:/workspace/drupal10/web/themes/custom
    env_file:
      - .env
 
  # nginx:
  #   image: nginx:1.25
  #   ports:
  #     - "80"
  #   volumes:
  #     - ../:/workspace
  #     - ./nginx.conf:/etc/nginx/nginx.conf

  db:
    image: mariadb:11
    ports:
      - 3306:3306
    env_file:
      - .env

  phpmyadmin:
    image: phpmyadmin:5
    ports:
      - 8080:80
    env_file:
      - .env

  backstop:
    image: backstopjs/backstopjs
    container_name: backstop
    command: remote
    env_file:
      - .env
    links:
      - d9gateway:drupal9
      - gateway:drupal10
    ports:
        - 3000:3000
    volumes:
      - ../data/backstop:/src