version: '3.3'

name: cmqcc

services:
  devcontainer:
    build:
      context: ./
      dockerfile: devcontainer/devcontainer.containerfile
    volumes:
      - ../:/workspace
      - /Users/ronan/.ssh:/root/.ssh:ro
      - /Users/ronan/.terminus:/root/.terminus
    links:
      - gateway:drupal
      - db
    env_file:
      - ../.env

  gateway:
    image: nginx:1.25
    links:
      - app
    ports:
      - 8010:80
    volumes:
      - ../:/workspace
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf

  app:
    build:
      context: ./
      dockerfile: app/app.containerfile
    links:
      - db
    volumes:
      - ../:/workspace
    env_file:
      - ../.env

  db:
    image: mariadb:11
    # ports:
    #   - 3306:3306
    env_file:
      - ../.env

  phpmyadmin:
    image: phpmyadmin:5
    ports:
      - 8080:80
    env_file:
      - ../.env

  backstop:
    image: backstopjs/backstopjs
    command: --config="/workspace/backstop.js/backstop.config.js" remote
    links:
      - gateway:drupal
    ports:
      - 3000:3000
    volumes:
      - ../:/workspace
    env_file:
      - ../.env
