x-service_defaults: &service_defaults
    env_file:
      - ./.env
      - ../.env
    volumes:
      - ../:/workspace

services:
  devcontainer:
    << : *service_defaults
    build:
      context: ./
      dockerfile: devcontainer/devcontainer.containerfile
    links:
      - db
      - gateway:report.local
      - gateway:drupal.local
      - gateway:backstop.local
      - gateway:reference.local

  gateway:
    # << : *service_defaults
    image: nginx:1.25
    links:
      - app
    ports:
      - 80:80
      - 8010
      - 8100
    volumes:
      - ../:/workspace
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf

  db:
    << : *service_defaults
    image: mariadb:11
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf:ro

  app:
    << : *service_defaults
    build:
      context: ./
      dockerfile: app/app.containerfile
    links:
      - db
    expose:
      - 9000

  phpmyadmin:
    << : *service_defaults
    image: phpmyadmin:5
    ports:
      - 8080:80

  sitespeed:
    image: sitespeedio/sitespeed.io
    command: -b chrome http://backdrop.local
    links:
      - gateway:drupal.local
      - gateway:backdrop.local
      - gateway:app.local
    volumes:
      - ../outbox/sitespeed.io:/sitespeed.io

  backstop:
    << : *service_defaults
    image: backstopjs/backstopjs
    command: --config="/workspace/.devcontainer/backstop.js/backstop.config.js" remote
    links:
      - gateway:backdrop.local
      - gateway:app.local
      - gateway:drupal.local
      - gateway:backstop.local
      - gateway:reference.local
