version: '3.3'

services:
  devcontainer:
    build:
      context: ./
      dockerfile: devcontainer/devcontainer.containerfile
    volumes:
      - ../:/workspace
    links:
      - gateway:drupal
    env_file:
      - .env 

  gateway:
    image: nginx:1.25
    links:
      - app
    ports:
      - 8010:80
    volumes:
      - ../:/workspace
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf

  app:
    build:
      context: ./
      dockerfile: drupal/drupal.containerfile
    links:
      - db
    volumes:
      - ../:/workspace
    env_file:
      - .env
 
  db:
    image: mariadb:11
    ports:
      - 3306:3306
    env_file:
      - .env

  phpmyadmin:
    image: phpmyadmin:5
    ports:
      - 8080:80
    env_file:
      - .env

  backstop:
    image: backstopjs/backstopjs
    container_name: backstop
    command: remote
    env_file:
      - .env
    links:
      - gateway:drupal
    ports:
        - 3000:3000
    volumes:
      - ../:/workspace
      - ../site/data/backstop:/src