version: '3.3'

services:
  devcontainer:
    build:
      context: ./
      dockerfile: devcontainer/devcontainer.containerfile
    volumes:
      - ../:/workspace
      # - /Users/ronan/.ssh:/root/.ssh:ro
      # - /Users/ronan/.terminus:/root/.terminus
    links:
      - gateway:drupal
      - db
    env_file:
      - ./.env
      - ../.env

  gateway:
    image: nginx:1.25
    links:
      - app
    ports:
      - 8010:80
    volumes:
      - ../:/workspace
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf

  app:
    build:
      context: ./
      dockerfile: app/app.containerfile
    links:
      - db
    expose:
      - 9000
    volumes:
      - ../:/workspace
    env_file:
      - ./.env
      - ../.env

  db:
    image: mariadb:11
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    env_file:
      - ./.env
      - ../.env

  phpmyadmin:
    image: phpmyadmin:5
    ports:
      - 8080:80
    env_file:
      - ./.env
      - ../.env

  # backstop:
  #   image: backstopjs/backstopjs
  #   command: --config="/workspace/.devcontainer/backstop.js/backstop.config.js" remote
  #   links:
  #     - gateway:drupal
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ../:/workspace
  #   env_file:
  #     - ./.env
  #     - ../.env
